"""
Django settings for django_backend project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3@e2&5vhi$$!_(9_3z7l#@@=fs1y6yszgj(2_7^m^ivfmh5l4r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*',]

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_HEADERS = ('*')


# Application definition

INSTALLED_APPS = [
    'daphne',
    'main_page',
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'channels',
    'drf_yasg', # 自动生成API
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django_backend.middleware.LegacyApiDeprecationMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_backend.wsgi.application'
# ASGI 设置（Websocket路由方式）
ASGI_APPLICATION = "django_backend.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',

        # 'ENGINE': 'django.db.backends.mysql', # 数据库类型
        # 'NAME': 'django', # 数据库名称
        # 'USER': 'root', # 用户名
        # 'PASSWORD': '12345677', # 密码
        # 'HOST': '127.0.0.1', # MySQL服务器主机地址
        # 'POST': '3306', # 主机地址端口号
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Hong_Kong'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# MQTT 相关设置

# MQTT_SERVER = '192.168.31.18'
MQTT_SERVER = '192.168.233.100'
MQTT_PORT = 1883
MQTT_KEEPALIVE = 60
# MQTT 用户名&密码仅作节点识别，并非真实需要登陆

MQTT_USER = 'Django'
MQTT_PASSWORD = '123456'

# MQTT 自动重连退避配置（秒）
MQTT_AUTO_RECONNECT_MIN_DELAY = 2
MQTT_AUTO_RECONNECT_MAX_DELAY = 90
MQTT_AUTO_RECONNECT_MULTIPLIER = 2

# 默认目标设备（用于 task_manager 与未指定设备的 recipe step）
# 请改成实际 ESP32 的 device_id，例如 esp32_7cdfa1e6d3cc
MQTT_DEFAULT_DEVICE_ID = os.environ.get('MQTT_DEFAULT_DEVICE_ID', 'esp32_1')

# ROS2 Bridge 相关配置
ROS2_BRIDGE_BASE_URL = os.environ.get('ROS2_BRIDGE_BASE_URL', 'http://127.0.0.1:9001')
ROS2_BRIDGE_TIMEOUT_SEC = float(os.environ.get('ROS2_BRIDGE_TIMEOUT_SEC', '5'))

# Channels 相关配置
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    }
}

# DRF 配置
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.openapi.AutoSchema',
}

# SWAGGER 相关设置
SWAGGER_SETTINGS = {
    'USE_SESSION_AUTH': False,          # 关闭 Django 登录框
    'JSON_EDITOR': True,
    'SHOW_EXTENSIONS': True,
    'SHOW_COMMON_EXTENSIONS': True,
    # 允许自动扫描函数视图
    'DEFAULT_AUTO_SCHEMA_CLASS': 'drf_yasg.inspectors.SwaggerAutoSchema',
}

STATIC_ROOT = BASE_DIR / 'staticfiles'
