# Generated by Codex on 2026-07-27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0034_spinning_motor_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentDataPoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device_type', models.CharField(blank=True, max_length=32, null=True)),
                ('device_id', models.CharField(blank=True, max_length=64, null=True)),
                ('metric_name', models.CharField(db_index=True, max_length=64)),
                ('metric_value', models.FloatField(blank=True, null=True)),
                ('metric_text', models.CharField(blank=True, max_length=128, null=True)),
                ('unit', models.CharField(blank=True, max_length=32, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'job',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='data_points',
                        to='main_page.batchjob',
                    ),
                ),
                (
                    'step_execution',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='data_points',
                        to='main_page.batchstepexecution',
                    ),
                ),
                (
                    'telemetry',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='data_points',
                        to='main_page.telemetryingest',
                    ),
                ),
            ],
            options={
                'ordering': ['timestamp', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='experimentdatapoint',
            index=models.Index(fields=['job', 'metric_name'], name='main_page_e_job_id_f7dcce_idx'),
        ),
        migrations.AddIndex(
            model_name='experimentdatapoint',
            index=models.Index(fields=['step_execution', 'metric_name'], name='main_page_e_step_ex_6aa74e_idx'),
        ),
        migrations.AddIndex(
            model_name='experimentdatapoint',
            index=models.Index(fields=['device_id', 'metric_name'], name='main_page_e_device__f0ac06_idx'),
        ),
    ]
