<?xml version="1.0"?>
<package format="3">
  <name>mycobot_pro600_gazebo</name>
  <version>0.1.0</version>
  <description>myCobot Pro600 ROS2 Gazebo 启动包，提供控制器、Gazebo 启动与模型生成入口。</description>

  <maintainer email="devnull@example.com">Platform G2</maintainer>
  <license>Proprietary</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>mycobot_pro600_description</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>xacro</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
