routes:
  arm.execute_trajectory:
    interface_type: action
    device_type: roboarm
    node: arm01
    action_topic: /arm01/execute_waypoint_trajectory
  gripper.set_force:
    interface_type: action
    device_type: gripper
    node: gripper01
